
Attr(attr string)
Size(attr string)
And()
EQ(v interface{})
NE(v interface{})
LT(v interface{})
LTE(v interface{})
GT(v interface{})
GTE(v interface{})
Between(lo, hi interface{})
In(vals ...interface{})
NotIn(vals ...interface{})
Not(exp *Builder)
OrGroup(exps ...*Builder)
Sub()
Exists()
NotExists()
OfType(t interface{})
BeginsWith(prefix interface{})
Contains(needle interface{})
